version: '2'
services:
  web:
    build: ./api
    #command: bash
    command: bash -c "alembic upgrade head && python app.py"
    volumes:
      - ./api:/code
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - //c/docker-data/petreon-db:/var/lib/postgresql

